-- PDF offer footer: generated-by line with system name placeholder (lv + en + ru).

with translations (translation_key, namespace, description, lv, en, ru) as (
  values
    (
      'exports.pdf.generated_by',
      'exports',
      'PDF offer page footer: small generated-by ad; {systemName} is a link to the system',
      'Piedāvājums ģenerēts {systemName} sistēmā',
      'Offer generated by the {systemName} system',
      'Предложение сформировано системой {systemName}'
    )
)
insert into public.site_translations (translation_key, namespace, description, values)
select
  translation_key,
  namespace,
  description,
  jsonb_build_object('lv', lv, 'en', en, 'ru', ru)
from translations
on conflict (translation_key) do update
set
  namespace = excluded.namespace,
  description = excluded.description,
  values = public.site_translations.values || excluded.values,
  updated_at = now();
